spring:
  application:
    name: blockpulse-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.blockchain.blockpulseservice: INFO
    org.springframework.web.socket: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  mempool.space:
    rest:
      fee-api-url: https://mempool.space/api/v1/fees/recommended
      mempool-info-api-url: https://mempool.space/api/mempool
    websocket:
      track-mempool-api-url: wss://mempool.space/api/v1/ws
  websocket:
    message-size-limit: 16777216
    reconnect-delay: 5000
    max-reconnect-attempts: 10
    reconnect:
      max-attempts: 10
      initial-delay-seconds: 5
      max-delay-seconds: 30
#    blockchain.info:
#      ws:
#        uri: wss://ws.blockchain.info/inv
  analysis:
    tx:
      local-cheap-percentile: 0.25
      local-normal-percentile: 0.75
      outliers-percentile-threshold: 0.99
      mempool-congestion-vbytes-threshold: 100