spring:
  application:
    name: blockpulse-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.blockchain.blockpulseservice: DEBUG
    org.springframework.web.socket: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

# Custom application properties
app:
  websocket:
    reconnect-delay: 5000
    max-reconnect-attempts: 10