spring:
  application:
    name: blockpulse-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.blockchain.blockpulseservice: INFO
    org.springframework.web.socket: INFO

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  rest:
    mempool.space:
      fee-api-url: https://mempool.space/api/v1/fees/recommended
      mempool-info-api-url: https://mempool.space/api/mempool
  websocket:
    message-size-limit: 4096
    reconnect-delay: 5000
    max-reconnect-attempts: 10
    reconnect:
      max-attempts: 10
      initial-delay-seconds: 5
      max-delay-seconds: 30
    blockchain.info:
      ws:
        uri: wss://ws.blockchain.info/inv
  analysis:
    tx:
      outliers-percentile-threshold: 99
      mempool-congestion-vbytes-threshold: 100