spring:
  application:
    name: blockpulse-service
  jackson:
    serialization:
      write-dates-as-timestamps: false
    default-property-inclusion: non_null

server:
  port: 8080

logging:
  level:
    com.blockchain.blockpulseservice: DEBUG
    org.springframework.web.socket: DEBUG

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always

app:
  websocket:
    message-size-limit: 4096
    reconnect-delay: 5000
    max-reconnect-attempts: 10
    reconnect:
      max-attempts: 10
      initial-delay-seconds: 5
      max-delay-seconds: 300
    blockchain.info:
      ws:
        uri: wss://ws.blockchain.info/inv